import { type RouteConfig, index, route, layout } from "@react-router/dev/routes";

export default [
  // ── SEO / Search Engine feeds ──────────────────────────────────────────────
  route("robots.txt", "routes/robots.tsx"),
  route("sitemap.xml", "routes/sitemap.tsx"),
  route("sitemap.xsl", "routes/sitemap-style.tsx"),

  // ── Public / standalone routes (no persistent shell) ──────────────────────
  route("login", "routes/login.tsx"),
  route("register", "routes/register.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("onboarding", "routes/onboarding.tsx"),
  route("select-company", "routes/select-company.tsx"),
  route("admin", "routes/admin.tsx"),
  route("admin/:tab", "routes/admin.tsx", { id: "admin-tab" }),
  route("invite/accept", "routes/invite-accept.tsx"),
  route("track", "routes/tracking.tsx"),
  route("verify", "routes/verify.tsx"),
  route("tender/:id", "routes/tender-public.tsx"),
  route("t/:id", "routes/tender-public.tsx", { id: "tender-short" }),

  // ── Authenticated routes (inside persistent AppShell) ─────────────────────
  layout("routes/_app.tsx", [
    index("routes/home.tsx"),

    // Dynamic company slug prefixed routes (e.g. /micro-padma-nusantara, /micro-padma-nusantara/dashboard)
    route(":companySlug", "routes/home.tsx", { id: "company-home" }),
    route(":companySlug/dashboard", "routes/home.tsx", { id: "company-dashboard" }),
    route(":companySlug/agentic-procurement", "routes/agentic-procurement.tsx", { id: "company-agentic-procurement" }),
    route(":companySlug/marketplace", "routes/marketplace.tsx", { id: "company-marketplace" }),
    route(":companySlug/marketplace/:id", "routes/marketplace-detail.tsx", { id: "company-marketplace-detail" }),
    route(":companySlug/cart", "routes/cart.tsx", { id: "company-cart" }),
    // Cart page removed — cart is now inline sidebar on marketplace
    route(":companySlug/my-pr", "routes/my-pr.tsx", { id: "company-my-pr" }),
    route(":companySlug/my-pr/:id", "routes/my-pr-detail.tsx", { id: "company-my-pr-detail" }),
    route(":companySlug/compare-review/:id", "routes/compare-review.tsx", { id: "company-compare-review" }),
    route(":companySlug/all-requests", "routes/all-requests.tsx", { id: "company-all-requests" }),
    route(":companySlug/rfq/:id", "routes/rfq-detail.tsx", { id: "company-rfq-detail" }),
    route(":companySlug/checkout", "routes/checkout.tsx", { id: "company-checkout" }),
    route(":companySlug/approvals", "routes/approvals.tsx", { id: "company-approvals" }),
    route(":companySlug/finance", "routes/finance.tsx", { id: "company-finance" }),
    route(":companySlug/company", "routes/company.tsx", { id: "company-company" }),
    route(":companySlug/catalogue", "routes/catalogue.tsx", { id: "company-catalogue" }),
    route(":companySlug/rfq", "routes/rfq.tsx", { id: "company-rfq" }),
    route(":companySlug/proposals", "routes/proposals.tsx", { id: "company-proposals" }),
    route(":companySlug/negotiation", "routes/negotiation.tsx", { id: "company-negotiation" }),
    route(":companySlug/my-rank", "routes/my-rank.tsx", { id: "company-my-rank" }),
    route(":companySlug/orders", "routes/orders.tsx", { id: "company-orders" }),
    route(":companySlug/receipts", "routes/receipts.tsx", { id: "company-receipts" }),
    route(":companySlug/payment-history", "routes/payment-history.tsx", { id: "company-payment-history" }),
    route(":companySlug/returns", "routes/returns.tsx", { id: "company-returns" }),
    route(":companySlug/debit-notes", "routes/debit-notes.tsx", { id: "company-debit-notes" }),
    route(":companySlug/bast", "routes/bast.tsx", { id: "company-bast" }),
    route(":companySlug/efaktur", "routes/efaktur.tsx", { id: "company-efaktur" }),
    route(":companySlug/notifications", "routes/notifications.tsx", { id: "company-notifications" }),
    route(":companySlug/account", "routes/account.tsx", { id: "company-account" }),
    route(":companySlug/pr-audit", "routes/pr-audit.tsx", { id: "company-pr-audit" }),
    route(":companySlug/tasks", "routes/tasks.tsx", { id: "company-tasks" }),

    // Fallback legacy paths
    route("agentic-procurement", "routes/agentic-procurement.tsx"),
    route("marketplace", "routes/marketplace.tsx"),
    route("marketplace/:id", "routes/marketplace-detail.tsx"),
    route("cart", "routes/cart.tsx"),  // kept for deep-link /cart?add= backwards compat
    route("my-pr", "routes/my-pr.tsx"),
    route("my-pr/:id", "routes/my-pr-detail.tsx"),
    route("compare-review/:id", "routes/compare-review.tsx"),
    route("all-requests", "routes/all-requests.tsx"),
    route("rfq/:id", "routes/rfq-detail.tsx"),
    route("checkout", "routes/checkout.tsx"),
    route("approvals", "routes/approvals.tsx"),
    route("finance", "routes/finance.tsx"),
    route("company", "routes/company.tsx"),
    route("catalogue", "routes/catalogue.tsx"),
    route("rfq", "routes/rfq.tsx"),
    route("proposals", "routes/proposals.tsx"),
    route("negotiation", "routes/negotiation.tsx"),
    route("my-rank", "routes/my-rank.tsx"),
    route("orders", "routes/orders.tsx"),
    route("receipts", "routes/receipts.tsx"),
    route("payment-history", "routes/payment-history.tsx"),
    route("returns", "routes/returns.tsx"),
    route("debit-notes", "routes/debit-notes.tsx"),
    route("bast", "routes/bast.tsx"),
    route("efaktur", "routes/efaktur.tsx"),
    route("notifications", "routes/notifications.tsx"),
    route("account", "routes/account.tsx"),
    route("pr-audit", "routes/pr-audit.tsx"),
    route("tasks", "routes/tasks.tsx"),

    // Catch-all
    route("*", "routes/404.tsx"),
  ]),
] satisfies RouteConfig;
